module org.mockito {
    requires java.instrument;
    requires jdk.attach; // GH #2952
    requires static org.opentest4j;
    requires static junit;
    requires static transitive net.bytebuddy;
    requires static transitive net.bytebuddy.agent;

    exports org.mockito;
    exports org.mockito.codegen;
    exports org.mockito.configuration;
    exports org.mockito.creation.instance;
    exports org.mockito.exceptions.base;
    exports org.mockito.exceptions.misusing;
    exports org.mockito.exceptions.verification;
    exports org.mockito.exceptions.verification.junit;
    exports org.mockito.exceptions.verification.opentest4j;
    exports org.mockito.hamcrest;
    exports org.mockito.invocation;
    exports org.mockito.junit;
    exports org.mockito.listeners;
    exports org.mockito.mock;
    exports org.mockito.plugins;
    exports org.mockito.quality;
    exports org.mockito.session;
    exports org.mockito.stubbing;
    exports org.mockito.verification;

    opens org.mockito;
    opens org.mockito.codegen;
    opens org.mockito.configuration;
    opens org.mockito.creation.instance;
    opens org.mockito.exceptions.base;
    opens org.mockito.exceptions.misusing;
    opens org.mockito.exceptions.verification;
    opens org.mockito.exceptions.verification.junit;
    opens org.mockito.exceptions.verification.opentest4j;
    opens org.mockito.hamcrest;
    opens org.mockito.invocation;
    opens org.mockito.junit;
    opens org.mockito.listeners;
    opens org.mockito.mock;
    opens org.mockito.plugins;
    opens org.mockito.quality;
    opens org.mockito.session;
    opens org.mockito.stubbing;
    opens org.mockito.verification;

    exports org.mockito.internal.configuration.plugins;
    exports org.mockito.internal.util.reflection;
    exports org.mockito.internal.creation.bytebuddy;

// TODO: Remove in future version
/*
exports org.mockito.internal.configuration;
exports org.mockito.internal.configuration.injection;
exports org.mockito.internal.configuration.injection.filter;
exports org.mockito.internal.configuration.injection.scanner;
exports org.mockito.internal.configuration.plugins;
exports org.mockito.internal.creation;
exports org.mockito.internal.creation.bytebuddy;
exports org.mockito.internal.creation.bytebuddy.inject;
exports org.mockito.internal.creation.instance;
exports org.mockito.internal.creation.proxy;
exports org.mockito.internal.creation.settings;
exports org.mockito.internal.creation.util;
exports org.mockito.internal.debugging;
exports org.mockito.internal.exceptions;
exports org.mockito.internal.framework;
exports org.mockito.internal.hamcrest;
exports org.mockito.internal.handler;
exports org.mockito.internal.invocation;
exports org.mockito.internal.invocation.finder;
exports org.mockito.internal.invocation.mockref;
exports org.mockito.internal.junit;
exports org.mockito.internal.listeners;
exports org.mockito.internal.matchers;
exports org.mockito.internal.progress;
exports org.mockito.internal.reporting;
exports org.mockito.internal.runners;
exports org.mockito.internal.runners.util;
exports org.mockito.internal.session;
exports org.mockito.internal.util;
exports org.mockito.internal.util.collections;
exports org.mockito.internal.util.concurrent;
exports org.mockito.internal.util.io;
exports org.mockito.internal.util.reflection;
exports org.mockito.internal.verification;
exports org.mockito.internal.verification.api;
exports org.mockito.internal.verification.argumentmatching;
exports org.mockito.internal.verification.checkers;

opens org.mockito.internal.configuration;
opens org.mockito.internal.configuration.injection;
opens org.mockito.internal.configuration.injection.filter;
opens org.mockito.internal.configuration.injection.scanner;
opens org.mockito.internal.configuration.plugins;
opens org.mockito.internal.creation;
opens org.mockito.internal.creation.bytebuddy;
opens org.mockito.internal.creation.bytebuddy.inject;
opens org.mockito.internal.creation.instance;
opens org.mockito.internal.creation.proxy;
opens org.mockito.internal.creation.settings;
opens org.mockito.internal.creation.util;
opens org.mockito.internal.debugging;
opens org.mockito.internal.exceptions;
opens org.mockito.internal.framework;
opens org.mockito.internal.hamcrest;
opens org.mockito.internal.handler;
opens org.mockito.internal.invocation;
opens org.mockito.internal.invocation.finder;
opens org.mockito.internal.invocation.mockref;
opens org.mockito.internal.junit;
opens org.mockito.internal.listeners;
opens org.mockito.internal.matchers;
opens org.mockito.internal.progress;
opens org.mockito.internal.reporting;
opens org.mockito.internal.runners;
opens org.mockito.internal.runners.util;
opens org.mockito.internal.session;
opens org.mockito.internal.util;
opens org.mockito.internal.util.collections;
opens org.mockito.internal.util.concurrent;
opens org.mockito.internal.util.io;
opens org.mockito.internal.util.reflection;
opens org.mockito.internal.verification;
opens org.mockito.internal.verification.api;
opens org.mockito.internal.verification.argumentmatching;
opens org.mockito.internal.verification.checkers;

 */
}
