package org.mockito.mock;

/**
 * Represents the name of the mock as shown in the verification failure reports, etc.
 */
public interface MockName {

    /**
     * the name
     */
    String toString();

    /**
     * default name means generated by Mockito. non-default means the user has named the mock at creation.
     */
    boolean isDefault();
}
